# pageContent
title: ByteLab - Sociedad científica UCB

#libraries
bulma: false
icons: true

# fonts
roboto: true

#components
hasNavBar: true
hasFooter: true

#deploy config
baseurl: ""
url: ""

#info
contact: jey.pc.07@gmail.com

# to change the logo replace logo.jpg in /assets/imaages
# to change the team picture  equipo.jpg in /assets/images