# pageContent
title: Binary lovers

#libraries
bulma: false
icons: true

# fonts
roboto: true

#components
hasNavBar: true
hasFooter: true

#info
contact: jaymi@gmail.com

# to change the logo replace logo.jpg in /assets/imaages